import db from '@/lib/prismadb';
import MenuAdmin from 'components/admin/MenuAdmin';
import AdminLayout from 'components/admin/main-layout/AdminLayout';
import { cookies, headers } from 'next/headers';
import React, { Suspense } from 'react';
import { useCurrentUserAdmin } from '@/lib/server/helperServer';
import HeaderAdmin from '@/components/admin/HeaderAdmin';

export const metadata = {
  title: 'Admin Create Next App',
  description: 'Generated by create next app',
}

async function getData() {
  const nextCookies = cookies()
  const token = nextCookies.get('token-admin')

  const res = await fetch(process.env.NEXTAUTH_URL + '/api/admin/auth/me', {
    headers: {
      authorization: `bearer ${token?.value}`
    }
  })
  if (!res.ok) {
    return {user: null}
  }

  return res.json();
}

export default async function AdminRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  // const { user: data } = await getData()

  // console.log(data)

  const data = await useCurrentUserAdmin()

  return (
    <AdminLayout userData={data}>
      {children}
    </AdminLayout>
  )
}