import db from '@/lib/prismadb';
import MenuAdmin from 'components/admin/MenuAdmin';
import AdminLayout from 'components/admin/main-layout/AdminLayout';
import { headers } from 'next/headers';
import React, { Suspense } from 'react';

export const metadata = {
  title: 'Admin Create Next App',
  description: 'Generated by create next app',
}

async function getData() {
  // await new Promise((res) => setTimeout(() => {
  //   return res(true)
  // }, 10000))
  const adminId = headers().get('adminId') || 0

  const user = await db.admin.findUnique({
    where: {
      id: +adminId
    },
    select: {
      id: true,
      email: true,
      name: true,
      image: true
    }
  })

  return user;
}

export default async function AdminRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const data = await getData();

  return (
    <AdminLayout userData={data}>{children}</AdminLayout>
  )
}