import '@/styles/globals.css';
import MenuAdmin from '@/ui/admin/MenuAdmin';
import React from 'react';

export const metadata = {
  title: 'Admin Create Next App',
  description: 'Generated by create next app',
}

async function getData() {
  const posts = await prisma.post.findMany();
  return posts;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const data = await getData();
  console.log(data)

  return (
    <div className='w-full min-h-screen bg-gray-100 text-[#333]'>
      <MenuAdmin/>
      <div>
        {children}
      </div>
    </div>
  );
}


"use client"
const LayoutAdmin = () => {
  return  {

  }
}