import React from 'react';

export const metadata = {
  title: 'Admin',
  description: 'Generated by Việt Hùng Ít',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
