import { AuthProvider } from '@/components/web/AuthProviders';
import Header from '@/components/web/Header';
import { getCurrentUser } from '@/lib/getCurrentUser';
import React from 'react';
import Footer from '@/components/web/Footer';
import Modal from '@/components/web/Modal';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function WebRootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: any
}) {
  const userData = await getCurrentUser()

  return (
    <div className={`min-h-screen flex flex-col bg-gray-100`}>
      <AuthProvider>
        <Header user={userData} />
        <div className="flex-grow flex items-stretch">
          <div className='w-full'>{children}</div>
        </div>
        {/* <div className="mt-auto"></div> */}
        <Footer />
        <Modal />
      </AuthProvider>
    </div>
  )
}
