import './default.css'
import './globals.css';
import React from 'react';
import MuiProvider from '@/components/MuiProvider';
import { Roboto } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='vi'>
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body id='__next' className={`overflow-y-scroll text-[#222]`}>
        <MuiProvider>
          {children}
        </MuiProvider>
      </body>
    </html>
  );
}
